title: SPIE/Optica Student Chapter
description: University Of Wisconsin — Madison
show_downloads: true
google_analytics:
markdown: kramdown
theme: jekyll-theme-leap-day
collections:
  pages:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "" # NB: all files in the project
      type: pages
    values:
      layout: default
